// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.apache.avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class Interop : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Interop"",""namespace"":""org.apache.avro"",""fields"":[{""name"":""intField"",""default"":1,""type"":""int""},{""name"":""longField"",""default"":-1,""type"":""long""},{""name"":""stringField"",""type"":""string""},{""name"":""boolField"",""default"":false,""type"":""boolean""},{""name"":""floatField"",""default"":0.0,""type"":""float""},{""name"":""doubleField"",""default"":-1000000000000.0,""type"":""double""},{""name"":""nullField"",""type"":""null""},{""name"":""mapField"",""type"":{""type"":""map"",""values"":{""type"":""record"",""name"":""Foo"",""namespace"":""org.apache.avro"",""fields"":[{""name"":""label"",""type"":""string""}]}}},{""name"":""unionField"",""type"":[""boolean"",""double"",{""type"":""array"",""items"":""bytes""}]},{""name"":""enumField"",""type"":{""type"":""enum"",""name"":""Kind"",""namespace"":""org.apache.avro"",""symbols"":[""A"",""B"",""C""]}},{""name"":""fixedField"",""type"":{""type"":""fixed"",""name"":""MD5"",""namespace"":""org.apache.avro"",""size"":16}},{""name"":""recordField"",""type"":{""type"":""record"",""name"":""Node"",""namespace"":""org.apache.avro"",""fields"":[{""name"":""label"",""type"":""string""},{""name"":""children"",""default"":[],""type"":{""type"":""array"",""items"":""Node""}}]}}]}");
		private int _intField;
		private long _longField;
		private string _stringField;
		private bool _boolField;
		private float _floatField;
		private double _doubleField;
		private object _nullField;
		private IDictionary<string,org.apache.avro.Foo> _mapField;
		private object _unionField;
		private org.apache.avro.Kind _enumField;
		private org.apache.avro.MD5 _fixedField;
		private org.apache.avro.Node _recordField;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Interop._SCHEMA;
			}
		}
		public int intField
		{
			get
			{
				return this._intField;
			}
			set
			{
				this._intField = value;
			}
		}
		public long longField
		{
			get
			{
				return this._longField;
			}
			set
			{
				this._longField = value;
			}
		}
		public string stringField
		{
			get
			{
				return this._stringField;
			}
			set
			{
				this._stringField = value;
			}
		}
		public bool boolField
		{
			get
			{
				return this._boolField;
			}
			set
			{
				this._boolField = value;
			}
		}
		public float floatField
		{
			get
			{
				return this._floatField;
			}
			set
			{
				this._floatField = value;
			}
		}
		public double doubleField
		{
			get
			{
				return this._doubleField;
			}
			set
			{
				this._doubleField = value;
			}
		}
		public object nullField
		{
			get
			{
				return this._nullField;
			}
			set
			{
				this._nullField = value;
			}
		}
		public IDictionary<string,org.apache.avro.Foo> mapField
		{
			get
			{
				return this._mapField;
			}
			set
			{
				this._mapField = value;
			}
		}
		public object unionField
		{
			get
			{
				return this._unionField;
			}
			set
			{
				this._unionField = value;
			}
		}
		public org.apache.avro.Kind enumField
		{
			get
			{
				return this._enumField;
			}
			set
			{
				this._enumField = value;
			}
		}
		public org.apache.avro.MD5 fixedField
		{
			get
			{
				return this._fixedField;
			}
			set
			{
				this._fixedField = value;
			}
		}
		public org.apache.avro.Node recordField
		{
			get
			{
				return this._recordField;
			}
			set
			{
				this._recordField = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.intField;
			case 1: return this.longField;
			case 2: return this.stringField;
			case 3: return this.boolField;
			case 4: return this.floatField;
			case 5: return this.doubleField;
			case 6: return this.nullField;
			case 7: return this.mapField;
			case 8: return this.unionField;
			case 9: return this.enumField;
			case 10: return this.fixedField;
			case 11: return this.recordField;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.intField = (System.Int32)fieldValue; break;
			case 1: this.longField = (System.Int64)fieldValue; break;
			case 2: this.stringField = (System.String)fieldValue; break;
			case 3: this.boolField = (System.Boolean)fieldValue; break;
			case 4: this.floatField = (System.Single)fieldValue; break;
			case 5: this.doubleField = (System.Double)fieldValue; break;
			case 6: this.nullField = (System.Object)fieldValue; break;
			case 7: this.mapField = (IDictionary<string,org.apache.avro.Foo>)fieldValue; break;
			case 8: this.unionField = (System.Object)fieldValue; break;
			case 9: this.enumField = (org.apache.avro.Kind)fieldValue; break;
			case 10: this.fixedField = (org.apache.avro.MD5)fieldValue; break;
			case 11: this.recordField = (org.apache.avro.Node)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
