// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.apache.avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class Node : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Node\",\"namespace\":\"org.apache.avro\",\"fields\":[{\"name\":\"l" +
				"abel\",\"type\":\"string\"},{\"name\":\"children\",\"default\":[],\"type\":{\"type\":\"array\",\"i" +
				"tems\":\"Node\"}}]}");
		private string _label;
		private IList<org.apache.avro.Node> _children;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Node._SCHEMA;
			}
		}
		public string label
		{
			get
			{
				return this._label;
			}
			set
			{
				this._label = value;
			}
		}
		public IList<org.apache.avro.Node> children
		{
			get
			{
				return this._children;
			}
			set
			{
				this._children = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.label;
			case 1: return this.children;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.label = (System.String)fieldValue; break;
			case 1: this.children = (IList<org.apache.avro.Node>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
