// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.foo
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class Bar : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Bar\",\"namespace\":\"org.foo\",\"fields\":[{\"name\":\"foo\",\"type" +
				"\":{\"type\":\"record\",\"name\":\"Foo\",\"namespace\":\"org.apache.avro.ipc.specific\",\"fiel" +
				"ds\":[]}}]}");
		private org.apache.avro.ipc.specific.Foo _foo;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Bar._SCHEMA;
			}
		}
		public org.apache.avro.ipc.specific.Foo foo
		{
			get
			{
				return this._foo;
			}
			set
			{
				this._foo = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.foo;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.foo = (org.apache.avro.ipc.specific.Foo)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
