name: CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core LTS SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: |
          dotnet restore
      - name: Build
        run: |
          dotnet build \
            --configuration Release \
            --no-restore
      - name: Pre-Test (AvroGen AVDL to AVSC)
        run: |
          chmod +x ./dotnet-cli-prets.bash
          ./dotnet-cli-prets.bash
        shell: bash        
      - name: Test
        run: |
          cd Pandora.Apache.Avro.IDL.To.Apache.Parquet.Unit.Tests
          dotnet test \
            --configuration Release \
            --logger "console;verbosity=detailed" \
            "./Pandora.Apache.Avro.IDL.To.Apache.Parquet.Unit.Tests.fsproj"

# References
#
# Building and testing .NET
# - https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# 
# Using jobs in a workflow > Defining prerequisite jobs
# - https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs
#
# Encrypted secrets
# - https://docs.github.com/en/actions/security-guides/encrypted-secrets
#
# Workflow syntax for GitHub Actions > Example: Excluding paths
# - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
